### ISSUE TITLE
Arcane Empowerment?

### ISSUE THREAD

**Issue by ghost** [Vae2009/ConRO_Mage#1]
Get this on login, lvl 60 arcane mage. It's a PvP talent. She's currently marked PvP but it's a timer ticking down from turning off War Mode.

`3x ConRO_Mage/mage.lua:265: attempt to index field 'ArcaneEmpowerment' (a number value)
[string "@ConRO_Mage/mage.lua"]:265: in function `NextSpell'
[string "@ConRO/core.lua"]:2471: in function `?'
[string "@DataStore/libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
_ = <table> {
 AbilityPurge = <function> defined @ConRO/buttons.lua:2791
 IsPvP = <function> defined @ConRO/helper.lua:50
 Dragonriding = <function> defined @ConRO/helper.lua:1131
 DestroyPurgableOverlays = <function> defined @ConRO/buttons.lua:1712
 modules = <table> {
 }
 CancelTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:147
 DefFetchBlizzard = <function> defined @ConRO/buttons.lua:2266
 ItemEquipped = <function> defined @ConRO/helper.lua:147
 PurgeWindowFrame = <function> defined @ConRO/buttons.lua:1075
 InterruptGlow = <function> defined @ConRO/buttons.lua:1875
 ScheduleTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:94
 TalentChosen = <function> defined @ConRO/helper.lua:69
 CreateDefenseOverlay = <function> defined @ConRO/buttons.lua:1282
 BurnPhase = <function> defined @ConRO_Mage/mage.lua:1068
 Heroism = <function> defined @ConRO/helper.lua:434
 ClassRGB = <table> {
 }
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 InvokeNextDef = <function> defined @ConRO/core.lua:2509
 ClearAbilityRaidBuffsIndependent = <function> defined @ConRO/buttons.lua:2720
 CreateRaidBuffsOverlay = <function> defined @ConRO/buttons.lua:1546
 InterruptFramePool = <table> {
 }
 UnitAura = <function> defined @ConRO/helper.lua:365
 DisplayNext2WindowFrame = <function> defined @ConRO/buttons.lua:900
 UNIT_ENTERED_VEHICLE = <function> defined @ConRO/core.lua:2284
 EnergyList = <table> {
 }
 RotationTimer = <table> {
 }
 ACTIONBAR_PAGE_CHANGED = <function> defined @ConRO/core.lua:2446
 DefSpells = <table> {
 }
 optionsFrame = Frame {
 }
 CreateCoolDownOverlay = <function> defined @ConRO/buttons.lua:1216
 MovementFramePool = <table> {
 }
 Spells = <table> {
 }
 GetName = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 IsSpellInRange = <function> defined @ConRO/helper.lua:856
 Dump = <function> defined @ConRO/buttons.lua:2628
 Colors = <table> {
 }
 RaidBuff = <function> defined @ConRO/helper.lua:522
 ClearAbilityInterruptIndependent = <function> defined @ConRO/buttons.lua:2696
 ToggleDamage = <function> defined @ConRO/buttons.lua:718
 Disable = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 PLAYER_CONTROL_LOST = <function> defined @ConRO/core.lua:2344
 Print = <function> defined @ConRO/core.lua:2036
 BurstMode = <function> defined @ConRO/helper.lua:81
 LEARNED_SPELL_IN_TAB = <function> defined @ConRO/core.lua:2446
 HideTauntGlow = <function> defined @ConRO/buttons.lua:1983
 HideDefenseGlow = <function> defined @ConRO/buttons.lua:1959
 CreateBurstButton = <function> defined @ConRO/buttons.lua:483
 Totem = <function> defined @ConRO/helper.lua:1119
 SlashUnlock = <function> defined @ConRO/buttons.lua:626
 SetDefaultModuleLibraries = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 rotationEnabled = true
 ItemReady = <function> defined @ConRO/helper.lua:943
 EnableModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 IterateEmbeds = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 RaidBuffsFramePool = <table> {
 }
 DefenseFramePool = <table> {
 }
 BlockAoE = <function> defined @ConRO/buttons.lua:759
 Interrupt = <function> defined @ConRO/helper.lua:1057
 ButtonFetch = <function> defined @Interfa`

**Comment by Vae2009** [comment]
FOund the issue, will be fixed in next upload. Thanks
